### ISSUE TITLE
Links with detailed information do not work

### ISSUE THREAD

**Issue by ArtemBiliksin** [MERA-Evaluation/MERA#7]
Hello! 

Links for detailed information on tasks do not work on the [official website of the MERA project](https://mera.a-ai.ru/ru):
* [page in Russian](https://mera.a-ai.ru/ru/tasks) - ruHHHH, ruDetox
* [page in English](https://mera.a-ai.ru/en/tasks) - ruDetox, ruEthics, ruHHH

**Comment by LSinev** [comment]
Seems working for me now...

**Comment by ArtemBiliksin** [comment]
Yeah, it's starting to work now. Thank you!
