### ISSUE TITLE
ruEthics test in the public leaderboard

### ISSUE THREAD

**Issue by ArtemBiliksin** [MERA-Evaluation/MERA#9]
Hello!

The ruEthics test produces fifteen numbers. Which of the fifteen numbers is recorded in the public leaderboard in the ruEthics column?
I looked at two examples (Qwen2-72B-Instruct, GPT4o) and concluded that `good.utilitarianism` is recorded. Am I correct in my conclusions?

**Comment by Alenush** [comment]
Hello! 

The point is to look at the corellation matrix (with 15 numbers). The mean between them is not representative and methodologically incorrect. However, on the board we needed only one number. We decided to add the lowest correlation among 15 corellations.

**Comment by ArtemBiliksin** [comment]
Hello, @Alenush !

Thanks for the reply! Now it all makes sense to me.
